import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import {BsFillMoonStarsFill} from 'react-icons/bs'
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai'
import waveHello from '../public/dev-ed-wave.png'
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react'




const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <>
    <div className={darkMode? "dark":""}>
      <Head>
        <title>ABRAR HAQUE's PORTFOLIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-slate-900'>
        <section className="min-h-screen">
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>DevelopedByAbrar</h1>
            <ul className='flex items-center'>
              <li className='text-2xl cursor-pointer dark:text-white'><BsFillMoonStarsFill onClick={()=>setDarkMode(!darkMode)}/></li>
              <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Abrar Haque</h2>
            <h3 className='text-2xl py-2 md:txt-3xl dark:text-white'>Developer and Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-xl mx-auto dark:text-white'>Providing all kinds of solution for your web presence. Make the best out of this digital era for your business and let us be a helping hand to your web services needs!</p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 mb-5 text-gray-600'>
            <AiFillTwitterCircle />
            <AiFillLinkedin />
            <AiFillYoutube />
          </div>
          <div className='relative bg-gradient-to-b from-teal-500 rounded-full h-80 w-80 mb-5 mx-auto overflow-hidden md:h-96 md:w-96'>
            <Image src={waveHello} alt={''} fill sizes="(max-width: 768px) 100vw,
              (max-width: 1200px) 50vw,
              33vw" style={{objectFit:'cover'}}></Image>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Services I Offer</h3>
            <p className='py-2 text-md leading-8 text-gray-800 dark:text-white'> It has been quite some time that we are providing professional and competetive web services. Our services include your regular <span className='text-teal-500'>Web</span> Design and Development, <span className='text-teal-500'>UX/UI</span> Design, Graphics Design, Search Engine Optimization <span className='text-teal-500'>(SEO)</span>, Digital Marketing & Content Writing. 
            </p>
            <p className='py-2 text-md leading-8 text-gray-800 dark:text-white'>We collaborate with a bunch of talented people to get the content delivered to you errorfree and as early as possible. We cherish for long term and repeated customers and thereore we are very service oriented.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 lg:h-100 lg:w-1/3'>
              <Image src={design} alt={""} width={100} height={100} className="mx-auto"></Image>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Designs</h3>
              <p className='py-2 dark:text-white'>Creating elegant desings suited for your needs using coherent design theories.</p>
              <h4 className='text-teal-500 py-4'>Design Tools I Use</h4>
              <p className='text-gray-800 py-1 dark:text-slate-300'>Adobe Photoshop</p>
              <p className='text-gray-800 py-1 dark:text-slate-300'>Adobe Illustrator</p>
              <p className='text-gray-800 py-1 dark:text-slate-300'>Figma</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 lg:h-100 lg:w-1/3'>
              <Image src={code} alt={""} width={100} height={100} className="mx-auto"></Image>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Clean Codes</h3>
              <p className='py-2 dark:text-white'>Writing clean codes, easy to maintain using best coding practices.</p>
              <h4 className='text-teal-500 py-4'>Coding Tools I Use</h4>
              <p className='text-gray-800 py-1 dark:text-slate-300'>React JS</p>
              <p className='text-gray-800 py-1 dark:text-slate-300'>Next JS</p>
              <p className='text-gray-800 py-1 dark:text-slate-300'>VC Code</p>
            </div>

            <div className='text-center shadow-lg p-10 rounded-xl my-10 lg:h-100 lg:w-1/3'>
              <Image src={consulting} alt={""} width={100} height={100} className="mx-auto"></Image>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Best Consultation</h3>
              <p className='py-2 dark:text-white'>Providing best consultation using the knowledge and expertise we have to uplift your business.</p>
              <h4 className='text-teal-500 py-4'>Design Tools I Use</h4>
              <p className='text-gray-800 py-1 dark:text-slate-300'>MIRO</p>
              <p className='text-gray-800 py-1 dark:text-slate-300'>Slack</p>
              <p className='text-gray-800 py-1 dark:text-slate-300'>Zoom</p>
            </div>
          </div>
        </section>
        
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='py-2 text-md leading-8 text-gray-800 dark:text-white'> It has been quite some time that we are providing professional and competetive web services. Our services include your regular <span className='text-teal-500'>Web</span> Design and Development, <span className='text-teal-500'>UX/UI</span> Design, Graphics Design, Search Engine Optimization <span className='text-teal-500'>(SEO)</span>, Digital Marketing & Content Writing. 
            </p>
            <p className='py-2 text-md leading-8 text-gray-800 dark:text-white'>We collaborate with a bunch of talented people to get the content delivered to you error-free and as early as possible. We cherish for long term and repeated customers and thereore we are very service oriented.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap justify-center'>
            <div className='basis-1/3'>
              <Image src={web1} alt={""} className='rounded-lg object-cover flex-1 h-100 w-100' priority={true}/>
            </div>
            <div className='basis-1/3'>
              <Image src={web2} alt={""} className='rounded-lg object-cover flex-1 h-100 w-100' priority={true}/>
            </div>
            <div className='basis-1/3'>
              <Image src={web3} alt={""} className='rounded-lg object-cover flex-1 h-100 w-100' priority={true}/>
            </div>
            <div className='basis-1/3'>
              <Image src={web4} alt={""} className='rounded-lg object-cover flex-1 h-100 w-100' priority={true}/>
            </div>
            <div className='basis-1/3'>
              <Image src={web5} alt={""} className='rounded-lg object-cover flex-1 h-100 w-100' priority={true}/>
            </div>
            <div className='basis-1/3'>
              <Image src={web6} alt={""} className='rounded-lg object-cover flex-1 h-100 w-100' priority={true}/>
            </div>
          </div>
        </section>
      </main>
      </div>
    </>
  )
}
